import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { getBooks, insertBook } from "@/utils/supabase";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  const [books, setBooks] = useState([]);

  // Function to fetch books from Supabase and update state
  const fetchBooks = async () => {
    const { data, error } = await getBooks(); // Assuming you have a function to fetch books from Supabase
    if (error) {
      console.error("Error fetching books:", error.message);
    } else {
      setBooks(data);
    }
  };

  useEffect(() => {
    fetchBooks(); // Fetch books when component mounts
  }, [])

  const [bookData, setBookData] = useState({
    book_name: '',
    author: '',
    genre: '',
    copies_given: 0
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setBookData({ ...bookData, [name]: value });
  };

  const handleSubmit = async (e) => {
    //e.preventDefault();
    if (bookData.book_name == '' || bookData.author == '' || bookData.genre == ''){
      return
    }
    const data = await insertBook(bookData);
    if (data) {
      setBookData({
        book_name: '',
        author: '',
        genre: '',
        copies_given: 0
      })
      fetchBooks() // Redirect to homepage after successful submission
    } else {
      // Handle error
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            <code className={styles.code}>Книги</code>
          </p>
        </div>

        <div className={styles.center}>
          <div className={styles.add}>
            <h2>Добавить книгу</h2>
            <form onSubmit={handleSubmit} className={styles.form}>
              <div className={styles.row}>
                <label htmlFor="book_name">Название книги:</label>
                <input
                  type="text"
                  id="book_name"
                  name="book_name"
                  value={bookData.book_name}
                  onChange={handleChange}
                />
              </div>
              <div className={styles.row}>
                <label htmlFor="author">Автор:</label>
                <input
                  type="text"
                  id="author"
                  name="author"
                  value={bookData.author}
                  onChange={handleChange}
                />
              </div>
              <div className={styles.row}>
                <label htmlFor="genre">Жанр:</label>
                <input
                  type="text"
                  id="genre"
                  name="genre"
                  value={bookData.genre}
                  onChange={handleChange}
                />
              </div>
              <div className={styles.row}>
                <label htmlFor="copies_given">Выдача:</label>
                <input
                  type="number"
                  id="copies_given"
                  name="copies_given"
                  value={bookData.copies_given}
                  onChange={handleChange}
                />
              </div>
              <button type="submit" className={styles.button}>Добавить</button>
            </form>
          </div>
          <div className={styles.list}>
            <h2>Книги:</h2>
            <div className={styles.books}>
              <div className={styles.table_row} id={styles.table_head}>
                  <p className={styles.bold}>Название</p>
                  <p className={styles.bold}>Автор</p>
                  <p className={styles.bold}>Жанр</p>
                  <p className={styles.bold}>Выдано</p>
              </div>
              {books.map((book) => (
                <div key={book.id} className={styles.table_row}>
                  <p>{book.book_name}</p>
                  <p>{book.author}</p>
                  <p>{book.genre}</p>
                  <p>{book.copies_given}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
